'blank_issues_enabled': true
'contact_links':
  - 'about': >
        Please report filtering issues, for example advertising filters
        misfiring or safe browsing false positives, using the form on our
        website
    'name': 'AdGuard filters issues'
    'url': 'https://link.adtidy.org/forward.html?action=report&from=github'
  - 'about': >
        Please check AdGuard Knowledgebase for more useful information about our products
    'name': 'Knowledgebase'
    'url': 'https://adguard.com/kb/'